// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:99531ce2-c6cd-4cbe-9de3-21b908b08b7a",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_RJzH52cF2",
    "aws_user_pools_web_client_id": "4q30sc7lqrvp6c80q7oud53k06",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://sojko6vyafcdhfhnwsr2jlaj6m.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
