// Notes app actions
export const ON_FETCH_NOTES_START = 'ON_FETCH_NOTES_START';
export const ON_FETCH_NOTES_SUCCESS = 'ON_FETCH_NOTES_SUCCESS';
export const ON_FETCH_NOTES_FAILURE = 'ON_FETCH_NOTES_SUCCESS';
