// Notes app actions

// Fetch notes
export const ON_FETCH_NOTES_START = 'ON_FETCH_NOTES_START';
export const ON_FETCH_NOTES_SUCCESS = 'ON_FETCH_NOTES_SUCCESS';
export const ON_FETCH_NOTES_FAILURE = 'ON_FETCH_NOTES_SUCCESS';

// Add notes
export const ON_ADD_NOTE_START = 'ON_ADD_NOTE_START';
export const ON_ADD_NOTE_SUCCESS = 'ON_ADD_NOTE_SUCCESS';
export const ON_ADD_NOTE_FAILURE = 'ON_ADD_NOTE_FAILURE';

// Edit Notes
export const ON_UPDATE_NOTE_START = 'ON_UPDATE_NOTE_START';
export const ON_UPDATE_NOTE_SUCCESS = 'ON_UPDATE_NOTE_SUCCESS';
export const ON_UPDATE_NOTE_FAILURE = 'ON_UPDATE_NOTE_FAILURE';

// Delete Notes
export const ON_DELETE_NOTE_START = 'ON_DELETE_NOTE_START';
export const ON_DELETE_NOTE_SUCCESS = 'ON_DELETE_NOTE_SUCCESS';
export const ON_DELETE_NOTE_FAILURE = 'ON_DELETE_NOTE_FAILURE';

// Type in form
export const ON_TYPE_FORM_START = 'ON_TYPE_FORM_START';
export const ON_TYPE_FORM_TITLE_SUCCESS = 'ON_TYPE_FORM_TITLE_SUCCESS';
export const ON_TYPE_FORM_DESCRIPTION_SUCCESS = 'ON_TYPE_FORM_DESCRIPTION_SUCCESS';

export const ON_TYPE_FORM_FAILURE = 'ON_TYPE_FORM_START';
